apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  dbPassword: 'password'
  mysql-password: 'password'
  mysql-replication-password: 'password'
  mysql-root-password: 'password'
