vcverifier:
  deployment:
    image:
      repository: quay.io/fiware/vcverifier
      tag: 2.0.5
      pullPolicy: Always
    logging: 
      level: DEBUG
      pathsToSkip: 
        - "/health"
    ssikit:
      auditorUrl: http://waltid-vcwaltid:7003
    verifier:
      tirAddress: https://tir.beka-t-m.apps.fiware.fiware.dev/v3/issuers
      did: did:web:marketplace.beka-t-m.fiware.dev:did
    configRepo:
      configEndpoint: http://ccs-credentials-config-service:8080/

  route:
    enabled: true
    host: verifier-marketplace.beka-t-m.apps.fiware.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod
  
