{{- if .Values.openshift -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-elasticsearch-rb
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
subjects:
  - kind: ServiceAccount
    name: elasticsearch-sa
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-elasticsearch-scc-anyuid
  apiGroup: rbac.authorization.k8s.io
{{- end -}}