apiVersion: v2
name: elasticsearch
description: Elasticsearch Chart

type: application
version: 0.1.0
appVersion: "7.5.1"

dependencies:
- name: elasticsearch
  version: 7.5.1
  repository: https://helm.elastic.co