elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  persistence:
    enabled: false

  rbac:
    create: false
    serviceAccountName: elasticsearch-sa

  image: "quay.io/i4trust/elasticsearch"
  imageTag: "7.5.1"
  imagePullPolicy: "IfNotPresent"

openshift: 
  enabled: true
