did: did:web:marketplace.beka-t-m.fiware.dev:did

route:
  enabled: true
  host: marketplace.beka-t-m.apps.fiware.fiware.dev
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  certificate:
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-aws-prod

vcwaltid:
  deployment:
    image:  
      repository: quay.io/fiware/waltid
      tag: 1.14.1-SNAPSHOT
      pullPolicy: Always
  api:
    core: 
      enabled: true
    auditor: 
      enabled: true
    signatory: 
      enabled: true
    custodian: 
      enabled: true
    essif: 
      enabled: true

  persistence: 
    enabled: true
    pvc:
      size: 1Gi

  templates:
    ActivationService.json: |
      {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "credentialSchema": {
          "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
          "type": "FullJsonSchemaValidator2021"
        },
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [{
            "names": ["CREATE_ISSUER"],
            "target": "did:elsi:packetdelivery"
          }]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": ["VerifiableCredential", "ActivationService"]
      }
    
