business-api-ecosystem:
  # is the target environment openshift?
  openshift: true

  initContainer:
    mysql: 
      image: "quay.io/i4trust/mysql"
    apis:
      image: "quay.io/i4trust/busybox:1.32"

  ## Marketplace OAuth and IdM configuration
  ##
  oauth:
    # URL of the FIWARE IDM used for user authentication
    server: https://idp-marketplace.domain.org
    # OAuth2 Client ID of the BAE applicaiton
    clientId: marketplace-id
    # -- Callback URL path of frontend logic proxy for receiving the access tokens
    callbackPath: /auth/fiware/callback
    # -- IDP provider for passport strategy (fiware, keycloak, github, ...)
    provider: fiware
    # -- Default role: Role to be used if no role is assigned to user (optional)
    defaultRole: seller

  siop:
    enabled: true
    clientId: marketplace-client
    verifier:
      host: https://verifier-marketplace.domain.org
    # Configuration for the Credential Config Service initiation
    ccs:
      endpoint: "http://ccs-credentials-config-service.demo.svc.cluster.local:8080"
      credentials:
        - type: "VerifiableCredential"
          trustedParticipantsLists: [
            "https://tir.domain.org"
          ]
          trustedIssuersLists: [
          ]
        - type: "MarketplaceUserCredential"
          trustedParticipantsLists: [
            "https://tir.domain.org"
          ]
          trustedIssuersLists: [
          ]

  ## External URL used to access the BAE frontend (logic proxy)
  ## Should match the host of the Ingress or Route of the Logic Proxy
  ##
  externalUrl: https://marketplace.domain.org

  ## Configuration for biz-ecosystem-apis component
  ##
  bizEcosystemApis:
    
    ## Service account
    serviceAccount:
      create: false

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    # Existing Secret
    existingSecret: bae-apis-secret

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE APIs image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-apis
        repository: quay.io/fiware/biz-ecosystem-apis
        ## -- tag of the image to be used
        tag: v8.1.0-rc1
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
      
    ## port that the APIs container uses
    port: 8080

    ## database configuration for APIs
    db:
      ## host of the database to be used
      host: mysql-bae
      ## password for connecting the database
      #password: dbPassword


  ## Configuration for biz-ecosystem-rss component
  ##
  bizEcosystemRss:
    
    ## Service account
    serviceAccount:
      create: false

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    # Existing Secret
    existingSecret: bae-rss-secret

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE RSS image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-rss
        repository: quay.io/fiware/biz-ecosystem-rss
        ## -- tag of the image to be used
        tag: v8.0.0
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
        #pullPolicy: Always
    
    ## port that the RSS container uses
    port: 8080
  
    ## database configuration for RSS
    db:
      ## host of the database to be used
      host: mysql-bae
      ## URL connection string of the database to be used
      url: jdbc:mysql://mysql-bae:3306/RSS
      ## password for connecting the database
      #password: dbPassword


  ## Configuration for biz-ecosystem-charging-backend component
  ##
  bizEcosystemChargingBackend:
    
    ## Service account
    serviceAccount:
      create: false

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    # Existing Secret
    existingSecret: bae-cb-secret

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE Charging backend image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-charging-backend
        repository: quay.io/fiware/biz-ecosystem-charging-backend
        ## -- tag of the image to be used
        tag: v8.1.0-dev-rc1
        ## -- specification of the image pull policy
        #pullPolicy: IfNotPresent
        pullPolicy: Always
          
    ## -- PVC configuration for charging backend plugins
    plugins:
      ## -- Enable the PVC for plugins storage
      enabled: true
      ## -- Annotations
      annotations:
        helm.sh/resource-policy: "keep"

    ## -- PVC configuration for charging backend media directories (/assets and /bills)
    media:
      # -- Enable the PVC for media storage
      enabled: true
    
    ## port that the charging backend container uses
    port: 8006

    # -- Loglevel
    loglevel: debug

    ## payment configuration
    payment:
      ## method: paypal or None (testing mode payment disconected)
      method: None

    ## database configuration for Charging backend (MongoDB)
    db:
      ## host of the database to be used
      host: mongodb
      ## Database name for connecting the database
      database: charging_db
      ## username for connecting the database
      user: charging
      ## password for connecting the database
      #password: charging

    ## -- Configuration for backing up the pvcs of the charging backend into a gcs-bucket
    backup:
      ## -- should the backup for file data be enabled
      enabled: false

    # -- Sets wehther to expect the user access token in each request from the logic proxy
    propagateToken: false

    # -- Base app path of charging backend (for versions < 8.1.0: /business-ecosystem-charging-backend, for versions >= 8.1.0: /opt/business-ecosystem-charging-backend)
    basePath: /opt/business-ecosystem-charging-backend

    # -- List of additional ENV vars to be set, e.g., to be used in asset plugins
    extraEnvVars:
      - name: BAE_PLUGIN_VC
        value: "ewogICJ0eXBlIiA6IFsgIlZlcmlmaWFibGVDcmVkZW50aWFsIiwgIkFjdGl2YXRpb25TZXJ2aWNlIiBdLAogICJAY29udGV4dCIgOiBbICJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsICJodHRwczovL3czaWQub3JnL3NlY3VyaXR5L3N1aXRlcy9qd3MtMjAyMC92MSIgXSwKICAiaWQiIDogInVybjp1dWlkOmM3ZTdkNGExLTc1NzktNDBhMy1iNDE4LTU5ZjZhOWYyZjZiMSIsCiAgImlzc3VlciIgOiAiZGlkOndlYjptYXJrZXRwbGFjZS5kc2JhLmZpd2FyZS5kZXY6ZGlkIiwKICAiaXNzdWFuY2VEYXRlIiA6ICIyMDIzLTA2LTA3VDA3OjQ1OjA2WiIsCiAgImlzc3VlZCIgOiAiMjAyMy0wNi0wN1QwNzo0NTowNloiLAogICJ2YWxpZEZyb20iIDogIjIwMjMtMDYtMDdUMDc6NDU6MDZaIiwKICAiZXhwaXJhdGlvbkRhdGUiIDogIjIwMzItMTItMDhUMTM6MDU6MDZaIiwKICAiY3JlZGVudGlhbFNjaGVtYSIgOiB7CiAgICAiaWQiIDogImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9GSVdBUkUtT3BzL2k0dHJ1c3QtcHJvdmlkZXIvbWFpbi9kb2NzL3NjaGVtYS5qc29uIiwKICAgICJ0eXBlIiA6ICJGdWxsSnNvblNjaGVtYVZhbGlkYXRvcjIwMjEiCiAgfSwKICAiY3JlZGVudGlhbFN1YmplY3QiIDogewogICAgImlkIiA6ICIwYjg3NjAwMC0zNmM3LTQ3ZWQtYjg5Ni01YjVlYzE2MzY2M2EiLAogICAgInJvbGVzIiA6IFsgewogICAgICAibmFtZXMiIDogWyAiQ1JFQVRFX0lTU1VFUiIgXSwKICAgICAgInRhcmdldCIgOiAiZGlkOndlYjpwYWNrZXRkZWxpdmVyeS5kc2JhLmZpd2FyZS5kZXY6ZGlkIgogICAgfSBdLAogICAgImVtYWlsIiA6ICJtYXJrZXRwbGFjZUBteW1haWwuY29tIgogIH0sCiAgInByb29mIiA6IHsKICAgICJ0eXBlIiA6ICJKc29uV2ViU2lnbmF0dXJlMjAyMCIsCiAgICAiY3JlYXRvciIgOiAiZGlkOndlYjptYXJrZXRwbGFjZS5kc2JhLmZpd2FyZS5kZXY6ZGlkIiwKICAgICJjcmVhdGVkIiA6ICIyMDIzLTA2LTA3VDA3OjQ1OjA2WiIsCiAgICAidmVyaWZpY2F0aW9uTWV0aG9kIiA6ICJkaWQ6d2ViOm1hcmtldHBsYWNlLmRzYmEuZml3YXJlLmRldjpkaWQjNmY0YzEyNTVmNGE1NDA5MGJjOGZmNzM2NWIxM2E5YjciLAogICAgImp3cyIgOiAiZXlKaU5qUWlPbVpoYkhObExDSmpjbWwwSWpwYkltSTJOQ0pkTENKaGJHY2lPaUpRVXpJMU5pSjkuLlRoU0pWNHZWaGx4WVUzTjdPU2s2LXRuS3ZkQUNmWTltaFJxQ1ZJZjBlTENDU2JrRXlZVjRzZXZkN0FDLUhHWUoyS1dtTXlKVG0tLWdOb2d0NUl1VGFhNS1vVGVnWUJUeVJJY190aFpneEo0NF83V2ZwTy13QVk0dXl1S3p0LVRZVmhRU1dRNWxBX0NwVDltTDcyTkFHUDR2bk5vVnZTa1hoSUNCX2c3YTJLcWw0eHNSLXdaNmh0VjhXNGJlRGV2aHUzYWpPLVE2NUtYUVBad0lub1VwV2gxcmNyRWl5Ukp6OXBJMzE0NmQ3NmlrakxEZTByUVNNTWttMGJEUTg2b3NuY3VHLUhZSWJ3VkY5eEtpZWI2V19NdXBtV2FaUlVudmV3am0xX1pRQ0ZyS3czVUNMNkplU2hkbzdMSnBNX2JSa1hjSU5FUFhCV0pwNzc0eXYxaXlpQSIKICB9Cn0="

    ## -- Configuration of local key and certificate for validation and generation of tokens
    token: 
      enabled: false
    


  ## Configuration for biz-ecosystem-logic-proxy component
  ##
  bizEcosystemLogicProxy:
    
    ## Service account
    serviceAccount:
      create: false

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    # Existing Secret
    existingSecret: bae-lp-secret
    
    ## -- statefulset specific configuration
    statefulset:
      ## -- configuration of the image to be used
      image:
        ## -- BAE Logic Proxy image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-logic-proxy
        repository: fiware/biz-ecosystem-logic-proxy
        ## -- tag of the image to be used
        tag: v8.1.0-dev
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
        #pullPolicy: IfNotPresent
    
    ## openshift specific route definition. Will not work on plain k8s
    route:
      ## -- should the deployment create openshift routes
      enabled: true
      # -- Routes that should be created
      routes:
        - host: marketplace.domain.org
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
          certificate:
            issuer: 
              kind: ClusterIssuer
              name: letsencrypt-aws-prod

    ## ingress configuration
    ## OpenShift: oc label namespace marketplace ingress=nginx
    ingress:
      ## should there be an ingress to connect keyrock with the public internet
      enabled: false
      

    ## port that the logic proxy container uses
    port: 8004

    ## Deployment in development or in production
    nodeEnvironment: development

    ## database configuration for Logic Proxy (MongoDB)
    db:
      # host of the database to be used
      host: mongodb
      # Database name for connecting the database
      database: belp_db
      # username for connecting the database
      user: belp
      # password for connecting the database
      #password: belp

    ## -- elasticsearch configuration
    elastic:
      ## -- indexing engine of logic proxy
      engine: elasticsearch
      ## -- URL of elasticsearch service
      url: elasticsearch-master:9200
      ## -- API version of elasticsearch
      version: 7.5

    # -- Base app path of logic proxy (for versions < 8.1.0: /business-ecosystem-logic-proxy, for versions >= 8.1.0: /opt/business-ecosystem-logic-proxy)
    basePath: /opt/business-ecosystem-logic-proxy
    #basePath: /business-ecosystem-logic-proxy

    ## -- Custom theme configuration
    theme:
      ## -- Enable theme
      enabled: true
      ## -- Name of the theme
      name: i4trust
      ## -- Size of PVC to be created
      size: 4Gi
      ## Image which holds the theme files
      image: quay.io/wi_stefan/bae-i4trust-theme:1.0.1
      # -- specification of the image pull policy
      imagePullPolicy: Always
      ## Path to the source theme files inside the container
      #  Files will be copied to /themes/{{name}} with the PVC mounted at /themes
      sourcePath: /bae-i4trust-theme

    ## -- Configuration for external IDPs
    externalIdp:
      # -- Enable usage of external IDPs
      enabled: true
      # -- Show login button for local IDP
      showLocalLogin: true

    # -- Sets wehther the logic proxy should propagate the user access token to the backend components
    propagateToken: false

    ## -- Configuration of local key and certificate for validation and generation of tokens
    token:
      enabled: false
  
