# Values for t3n/mysql Helm Chart
#
# Chart values file:
# ref: https://github.com/t3n/helm-charts/blob/master/mysql/values.yaml
#

image: "mysql"
imageTag: "5.7"

existingSecret: mysql-secret

## Security context (might be necessary on OpenShift)
#securityContext:
#  enabled: false
