# Values for bitnami/mongodb Helm Chart
#
# Chart values file:
# ref: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
#

image:
  ## Bitnami MongoDB image name
  ##
  repository: bitnami/mongodb
  ## Bitnami MongoDB image tag
  ## ref: https://hub.docker.com/r/bitnami/mongodb/tags/
  ##
  tag: 4.4.13
  
## MongoDB architecture. Allowed values: standalone or replicaset
##
architecture: standalone

## Use StatefulSet instead of Deployment when deploying standalone
##
useStatefulSet: false

## MongoDB Authentication parameters
##
auth:
  ## Enable authentication
  ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
  ##
  enabled: true
  ## MongoDB root password
  ## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  rootPassword: password

serviceAccount:
  create: true
rbac:
  create: true
  rules:
    - apiGroups:
        - security.openshift.io
      resourceNames:
        - anyuid
      resources:
        - securitycontextconstraints
      verbs:
        - use

## initdb scripts
## Specify dictionary of scripts to be run at first boot
##
## This creates the required databases and users for the charging backend
## and logic proxy (belp) BAE components. Make sure to set these DB user
## configurations and databases for the corresponding components.
##
## If you omit the creation of databases and users during deployment, make sure
## to create these databases and users afterwards manually before proceeding with the
## BAE deployment.
##
initdbScripts:
  init_db.js: |
    // Setup charging DB
    db = db.getSiblingDB('charging_db');
    db.createUser(
    {
      user: "charging",
      pwd: "charging-password",
      roles: [
        {
          role: "readWrite",
          db: "charging_db"
        }
      ]
    });
    // Setup proxy DB
    db = db.getSiblingDB('belp_db');
    db.createUser(
    {
      user: "belp",
      pwd: "belp-password",
      roles: [
        {
          role: "readWrite",
          db: "belp_db"
        }
      ]
    });
## MongoDB pods' Security Context. (might be necessary on OpenShift)
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
#podSecurityContext:
#  enabled: false

## MongoDB containers' Security Context (main and metrics container). (might be necessary on OpenShift)
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
#containerSecurityContext:
#  enabled: false
