apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-root-password: 'password'
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-bae-envs-secret
type: Opaque
stringData:
  MONGO_BAE_BELP_PW: 'password'
  MONGO_BAE_CHARGING_PW: 'password'
